name: 'Prepare clojure env'
description: 'Prepare clojure enviroment for build'
runs:
  using: "composite"
  steps:
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Helsinki"

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@4.0
      with:
        lein: 2.9.1
