name: 'Prepare clojure env'
description: 'Prepare clojure enviroment for build'
runs:
  using: "composite"
  steps:
    - name: Cache local Maven repository
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 21
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
      with:
        java-version: '21'
        distribution: 'temurin'

    - uses: szenius/set-timezone@1f9716b0f7120e344f0c62bb7b1ee98819aefd42 # v2.0
      with:
        timezoneLinux: "Europe/Helsinki"

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@4c7a6f613e5089821bb3bb2a33a3ee115578580d # 13.6.1
      with:
        lein: 2.9.1
