sudo: required
language: clojure

jdk:
  - openjdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "U4otoOwJWm/9pH2eKdwwJqz3hj5nJrd1DmFTieL5UztIo4gSHajSyRnUrs/H40M14Xabm0iKiTDIL68T6Q7Q8g1qXJfdgnW126vO/TIy/qFpvdOt952UCJtCaAJQUj7t8NimGX0H6+scqET2RBwvH+xEeZ4Oq3JdNOw4MprW94mYX6WKu7zm3FAt5xFoTSmNirVQ3p9+F/8oGsiuFrqA6FcJUN08sx1KrClnA3m37bawePQUSAtWoUu5Ul/OV+xZ8vZ2emKoiCM2WJXIFj7KlAMgGNreRRxWqstZELMtUJhcTUyw8Zngo62lfpOUmIJ3pBRBk4UJGUgPot9q5T32pEbeYPLXbpTbpCjk6+fEudVnHiGotLAD7RTKdx9JSpH5aE0Cbk51TvxvubHF88ey7fTezAVeR7eEvBRGUVpIZ+6oJZiG2Ywdygay4+VMEiyL0q6edxOmI7WPBywJUOMQkF01Z6jhuKPmvuDDGTbPwf0L7LNrxazwnB8Ylc6mFLGmnX8ELxkhnrE0oGRNEpVeA7T8/1+7JEipmdVFlA/t1MHDCWNwzV2Ji7EGvYCyg5uCdyxLI5YLeGWLC26HePxpQ4+lYiOtuG2s79Y9nsffTzJjxewZaFhUnwl+YCAhost4VozGkSP8f90gx6eR3D8cqvUaceLugU91i+XoyqTtxHw="
    # AWS_SECRET_ACCESS_KEY
    - secure: "U0sdbO2m4Y5FlSPB0Yk/k9L2xyChgksWChFJq6l1jqjry/44u7iCiJRzj9sZWp5LAjPrn5ZEwRrAshmVo8C17odbL0jZXkPjJd0wgxfOfniiVtYSXK59KvHw7fsN1T+3QBryv/PFNmcCDNOSkc4GitIYBqu+4n+zNBIdigmiw/Wth1lNBN0RQ0dbWJLBz5MF6bmYJWwZHC34k9SLLrTC+rBpNzLWlaE51OcKQy9LgnO1qJrHwiZxBFmpCd3GS2Jzg6Fjreu25bq0z6j8s5LKSZ2wjcMESHJ43Xz4/2c34EFjhjCPSjQ9CMef8+yewAO91QnVfn0fcHDNTsUWDpPX9fDA3ExCxuqnU8KyRGP5z7sdY5sgyDPNx5bCYTz9HBza7jeLDnDSkuQoHAuniWBCm+z/HUMtZURlBeVpDQrwvtNUCd5EcZ77TkljxEmTGV+q0oPBKRGg5Oh1eG9CbUuV/BBunccqmmw52FU/bTSoqk5hrtY9XesyEmWfuRVlYb073mVvRNyzopxpfyJaGx850bWCIhXFOmpC8zzqC9Ra52OIDb/kpPr/bY0mcJ08rELwaTxnhZnXQx/NwdhrPLdVht2ZA+FfFHaFNUnXec/Sqr5ZmdX7zEtkY0BZCOrEoVBNiAb3b9coO804TnbUJYUw9gvhJNS32pFwFkBEEP0X0Ug="

install:
  - export TZ=Europe/Helsinki
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh

script:
  - ./ci/build_travis.sh uberjar
  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh

  - mv target/uberjar/oti.jar $DOCKER_BUILD_DIR/artifact/oti.jar
  - cp -vr oph-configuration $DOCKER_BUILD_DIR/config/
  - ./ci-tools/build/build-fatjar.sh oti

deploy:
  - provider: script
    script: ./ci-tools/build/upload-image.sh oti;
    on:
      all_branches: true
