DROP TABLE IF EXISTS module_score;
--;;
DROP TABLE IF EXISTS section_score;
--;;
DROP TABLE IF EXISTS payment;
--;;
DROP TYPE IF EXISTS payment_type;
--;;
DROP TYPE IF EXISTS payment_state;
--;;
DROP TABLE IF EXISTS registration;
--;;
DROP TYPE IF EXISTS registration_state;
--;;
DROP TABLE IF EXISTS participant;
--;;
DROP TABLE IF EXISTS exam_session;
--;;
DROP TABLE IF EXISTS module;
--;;
DROP TABLE IF EXISTS section;
--;;
DROP TABLE IF EXISTS exam;